### ISSUE TITLE
xSushi-Staker

### ISSUE THREAD

**Issue by mil0xeth** [mil0xeth/Strategy-xSushi-Staker#1]
# Protocol name: Sushi
Brief Strategy Description:
- The strategy stakes Sushi to xSushi.
 
Claiming a strategy
Due Diligence Review Protocol Due Diligence and Path to Prod: https://hackmd.io/@mil0xeth/HyNuUnZ85

Once a strategy's due diligence has been approved by the team, the strategist can begin codifying it for code review Strategy Review 

Repo: https://github.com/mil0xeth/Strategy-xSushi-Staker
Commit (hash): https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/70445301f61ccf676b402083d332816ec0fc6d3e
Deployment address on ape.tax: [0x0ef566227a2cc876120b749c8af0600d2e12143b](https://etherscan.io/address/0x0ef566227a2cc876120b749c8af0600d2e12143b#code)
 
Additional References or Repo (Link to underlying protocols or relevant documents):
Previous Sushi References

Review Ongoing By: 
- [x] @tonkers-kuma
- [x] @newmickymousse
- [x] @rareweasel 

Review Completed By: 
- [x] @tonkers-kuma
- [x] @newmickymousse
- [x] @rareweasel

**Comment by decaf-addict** [comment]
suggestion: Use `xSushi.leave(balanceOfXSushi())` instead to ensure all xSushi leaves without needing any any conversion (in case xSushi price is manipulated). Then return `balanceOfWant()`
https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/4c0a9dafb9053669f9f22681b1c589422c0ce0a0/contracts/Strategy.sol#L101

**Comment by decaf-addict** [comment]
LGTM. Short and simple!

**Comment by mil0xeth** [comment]
Awesome, thanks!

> suggestion: Use `xSushi.leave(balanceOfXSushi())` instead to ensure all xSushi leaves without needing any any conversion (in case xSushi price is manipulated). Then return `balanceOfWant()`
> 
> https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/4c0a9dafb9053669f9f22681b1c589422c0ce0a0/contracts/Strategy.sol#L101

Good catch, also more gas efficient this way. Implemented in commit 1f84e6ebb648839224899a730a7e0f76ad3e7501

**Comment by newmickymousse** [comment]
LGTM

**Comment by rareweasel** [comment]
Question:

Please, could you add screenshot with the tests passing?

**Comment by rareweasel** [comment]
Suggestion:

The imports (`SafeMath` / `SafeERC20`) are not required. They are already imported in `BaseStrategy`

https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L11-L12

Also, the `using ... for...` statements are not required.

https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L26
https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L24

**Comment by rareweasel** [comment]
Suggestion:

Please, to make it more readable please change [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) constant name (and also please put it in uppercase).

Also, please, remove [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L33-L35) commented code.

**Comment by rareweasel** [comment]
Question:

Just curious, why are you using 1e36 [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) instead of 1e18? Shouldn't 1e18 be enough?

**Comment by rareweasel** [comment]
Question:

Maybe I am missing something, but I think we don't need this `checkAllowance` call [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L107).

**Comment by rareweasel** [comment]
Suggestion:

I would make these view functions `public` or `external`.

https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L132
https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L136
https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L140

They might help us to debug any issue.

**Comment by rareweasel** [comment]
Question:

Would it be useful to have [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L92) calc in a public view function (passing the amount as parameter)?

`_amountNeeded.sub(wantBalance).mul(BigNumber).div(sushiPerXSushi()))`

**Comment by rareweasel** [comment]
Question:

Would it be useful to have a `withdraw` or `unstake` emergency function with access limited in case of an emergency?

Example: 
https://github.com/tonkers-kuma/strategy-ssb/blob/main/contracts/Strategy.sol#L463

**Comment by mil0xeth** [comment]
Hi rareweasel,
Thanks a lot for your feedback. I've implemented your changes in Commit https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/ab2d26de0666bf6caef69a5f32f53ec017e924aa.

> Please, could you add screenshot with the tests passing?

Here's a screenshot of all the tests passing:
![sushistaking](https://user-images.githubusercontent.com/96582887/169333636-15bbbdab-19e4-4949-a9bf-0c3287755e26.png)

> Suggestion:
> The imports (`SafeMath` / `SafeERC20`) are not required. They are already imported in `BaseStrategy`
> Also, the `using ... for...` statements are not required.

Thanks, good to know. We could update the yearn brownie mix with that fix as well.

> Suggestion: 
> Please, to make it more readable please change [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) constant name (and also please put it in uppercase).

Changed from "BigNumber" to "AVOID_ROUNDING_DECIMALS". 

> Question:
> Just curious, why are you using 1e36 [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) instead of 1e18? Shouldn't 1e18 be enough?

Unfortunately, it seems 1e18 is not enough as there is still a rounding error from the 1e18 ratio otherwise leading to small amount of Wei being lost. In additional tests, it seems 1e27 is enough.

> Also, please, remove [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L33-L35) commented code.

Done.
>Question:
>Maybe I am missing something, but I think we don't need this checkAllowance call [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L107).

Good catch, fixed.

> Suggestion:
> I would make these view functions public or external.
> https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L132
> https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L136
> https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L140
> They might help us to debug any issue.

I was torn if the gas efficiency of keeping them internal would outweigh the usefulness of having them as public functions. But I see the point that the debugging efficiency might take precedence. Changed these functions to public.

> Question:
> Would it be useful to have [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L92) calc in a public view function (passing the amount as parameter)?

Considering unstaking xSushi is 100% liquid, it's highly likely the funds will at all times be 100% in xSushi until withdrawal. The distribution does not need to be monitored. How much xSushi would be unlocked for an amount of Sushi required is already viewable by sushiPerXSushi(). 

> Question:
> Would it be useful to have a withdraw or unstake emergency function with access limited in case of an emergency?
> Example: https://github.com/tonkers-kuma/strategy-ssb/blob/main/contracts/Strategy.sol#L463

Implemented an emergencyUnstakeXSushi(uint256 _amount) function for emergency unstaking of xSushi.

**Comment by rareweasel** [comment]
> Hi rareweasel, Thanks a lot for your feedback. I've implemented your changes in Commit [ab2d26d](https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/ab2d26de0666bf6caef69a5f32f53ec017e924aa).
> 
> > Please, could you add screenshot with the tests passing?
> 
> Here's a screenshot of all the tests passing: ![sushistaking](https://user-images.githubusercontent.com/96582887/169333636-15bbbdab-19e4-4949-a9bf-0c3287755e26.png)
> 
> > Suggestion:
> > The imports (`SafeMath` / `SafeERC20`) are not required. They are already imported in `BaseStrategy`
> > Also, the `using ... for...` statements are not required.
> 
> Thanks, good to know. We could update the yearn brownie mix with that fix as well.
> 
> > Suggestion:
> > Please, to make it more readable please change [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) constant name (and also please put it in uppercase).
> 
> Changed from "BigNumber" to "AVOID_ROUNDING_DECIMALS".
> 
> > Question:
> > Just curious, why are you using 1e36 [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) instead of 1e18? Shouldn't 1e18 be enough?
> 
> Unfortunately, it seems 1e18 is not enough as there is still a rounding error from the 1e18 ratio otherwise leading to small amount of Wei being lost. In additional tests, it seems 1e27 is enough.
> 
> > Also, please, remove [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L33-L35) commented code.
> 
> Done.
> 
> > Question:
> > Maybe I am missing something, but I think we don't need this checkAllowance call [here](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L107).
> 
> Good catch, fixed.
> 
> > Suggestion:
> > I would make these view functions public or external.
> > https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L132
> > https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L136
> > https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L140
> > They might help us to debug any issue.
> 
> I was torn if the gas efficiency of keeping them internal would outweigh the usefulness of having them as public functions. But I see the point that the debugging efficiency might take precedence. Changed these functions to public.
> 
> > Question:
> > Would it be useful to have [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L92) calc in a public view function (passing the amount as parameter)?
> 
> Considering unstaking xSushi is 100% liquid, it's highly likely the funds will at all times be 100% in xSushi until withdrawal. The distribution does not need to be monitored. How much xSushi would be unlocked for an amount of Sushi required is already viewable by sushiPerXSushi().
> 
> > Question:
> > Would it be useful to have a withdraw or unstake emergency function with access limited in case of an emergency?
> > Example: https://github.com/tonkers-kuma/strategy-ssb/blob/main/contracts/Strategy.sol#L463
> 
> Implemented an emergencyUnstakeXSushi(uint256 _amount) function for emergency unstaking of xSushi.

Perfect, thanks for the updates. I will review the diff.

**Comment by rareweasel** [comment]
> Suggestion:
> 
> Please, to make it more readable please change [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L30) constant name (and also please put it in uppercase).
> 
> Also, please, remove [this](https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/master/contracts/Strategy.sol#L33-L35) commented code.

Thanks for the updates.

The only pending change is the commented code.

Apart from that, overall LGTM.

**Comment by rareweasel** [comment]
Comment:

I created the issue for the risk framework [here](https://github.com/yearn/yearn-watch-legacy/issues/332).

**Comment by rareweasel** [comment]
Reviewed the latest commit and LGTM

**Comment by rareweasel** [comment]
Please, add the strategy address here once it is deployed

**Comment by mil0xeth** [comment]
> Please, add the strategy address here once it is deployed

The strategy was added on ape.tax on 19. May 2022, so I've updated the initial post with the strategy's deployement address: [0x0ef566227a2cc876120b749c8af0600d2e12143b](https://etherscan.io/address/0x0ef566227a2cc876120b749c8af0600d2e12143b#code)

**Comment by dudesahn** [comment]
What is the point of this helper function? Seems like a waste of gas instead of just doing unlimited approval in the constructor. You're going to set approval to unlimited anyway, and will be checking this every time
https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/99897cef8a2bd91ea988d1b5e3cdfe4506c38414/contracts/Strategy.sol#L66

**Comment by dudesahn** [comment]
I would also highly recommend overriding the baseStrategy harvestTrigger method. I've modified a trigger from my convex template, which you can see here for functions/state vars that are referenced below:
```
    // use this to determine when to harvest
    function harvestTrigger(uint256 callCostinEth)
        public
        view
        override
        returns (bool)
    {
        // Should not trigger if strategy is not active (no assets and no debtRatio). This means we don't need to adjust keeper job.
        if (!isActive()) {
            return false;
        }

        // check if the base fee gas price is higher than we allow. if it is, block harvests.
        if (!isBaseFeeAcceptable()) {
            return false;
        }

        // trigger if we want to manually harvest, but only if our gas price is acceptable
        if (forceHarvestTriggerOnce) {
            return true;
        }

        StrategyParams memory params = vault.strategies(address(this));
        // harvest once we reach our maxDelay if our gas price is okay
        if (block.timestamp.sub(params.lastReport) > maxReportDelay) {
            return true;
        }

        // harvest our credit if it's above our threshold
        if (vault.creditAvailable() > creditThreshold) {
            return true;
        }

        // otherwise, we don't harvest
        return false;
    }
```
Feel free to ping me with any questions about any of these methods :)

**Comment by dudesahn** [comment]
Other than these two items, LGTM

**Comment by mil0xeth** [comment]
> What is the point of this helper function? Seems like a waste of gas instead of just doing unlimited approval in the constructor. You're going to set approval to unlimited anyway, and will be checking this every time
> 
> https://github.com/mil0xeth/Strategy-xSushi-Staker/blob/99897cef8a2bd91ea988d1b5e3cdfe4506c38414/contracts/Strategy.sol#L66

Agreed. That helper function is a relict of when it was used in more places, but after some optimizations it was actually only being used in one place making it obsolete, so I set the approval now in the constructor as you proposed.
First commit with just the gas optimization change: https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/c8cc02b16736886a6fbb7254f52f03f0768589b5

> I would also highly recommend overriding the baseStrategy harvestTrigger method. I've modified a trigger from my convex template, which you can see here for functions/state vars that are referenced below:

Thanks a lot for the modified harvestTrigger override. Micky and I were discussing already that we want to make the strategy more automized, so this is really useful input. I've set it up now with a 35 days maxReportDelay based on our calculation of return from TVL and considering that the strategy is not compounding. I've also put a 500k sushi creditThreshold (5e5 * 1e18) for automatic harvest upon such big deposits. Have a look in the following commit https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/441c294c3459cedd2d8c6fb6596202589a15979b

Here are all the tests passing on this newest commit https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/441c294c3459cedd2d8c6fb6596202589a15979b
![sushitests](https://user-images.githubusercontent.com/96582887/173682182-6b02001e-5869-4933-8b63-2e820cc0c495.png)

**Comment by dudesahn** [comment]
one minor comment I added to make the `creditThreshold` state var public and then LGTM :)

**Comment by dudesahn** [comment]
FYI just looked it up because I didn't know, but internal is the default state visibility if you don't specify

**Comment by mil0xeth** [comment]
Awesome, thanks man! The latest commit https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/eaabacf6b2ad5bdfd9906cd08c4a256020e3b2da now includes all proposed changes & all tests pass on this commit as well.

**Comment by newmickymousse** [comment]
@rareweasel can we get a LGTM with the new changes so I deploy the strat?

**Comment by newmickymousse** [comment]
Deployed contract: https://etherscan.io/address/0xb6abbd5594b344f17af8d9a83869c3660ea9a6bd#code

**Comment by rareweasel** [comment]
I've reviewed these 4 commits (the last 4 commits since my lgtm):

https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/c8cc02b16736886a6fbb7254f52f03f0768589b5
https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/441c294c3459cedd2d8c6fb6596202589a15979b
https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/dc3b2d10d40f2122fac95f75bf8bc6f6a811bdbe
https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/eaabacf6b2ad5bdfd9906cd08c4a256020e3b2da

LGTM

**Comment by rareweasel** [comment]
> Deployed contract: https://etherscan.io/address/0xb6abbd5594b344f17af8d9a83869c3660ea9a6bd#code

I compared the latest commit (https://github.com/mil0xeth/Strategy-xSushi-Staker/commit/dc3b2d10d40f2122fac95f75bf8bc6f6a811bdbe) and the deployed contract address and lgtm.

**Comment by rareweasel** [comment]
Suggestion:

Please, for tracking purposes, consider creating a new issue when making improvements to a strategy that is already in the reviewed column.
